# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.6.1-node-browsers
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
          
      - image: circleci/postgres:9.6.2-alpine
        environment: # environment variables for database
          POSTGRES_USER: root
          POSTGRES_DB: bookstore_test

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run: gem update --system
      - run: gem install bundler
      - run: bundle install
      - run: rails db:create db:migrate
      - run: rspec spec